### ISSUE TITLE
Can I use advanced formatting options with direct reference to chartist API? 

### ISSUE THREAD

**Issue by jensstruemper** [paradox41/angular2-chartist#52]
Hi there, 
I'd like to use some more advanced formatting options (my data contains holes) and stumbled over an example on the chartist examples page "Filled holes in data". Now I'm wondering if and how I could use `Chartist.Interpolation.cardinal` through the angular2-chartist wrapper. 

```
{
  fullWidth: true,
  chartPadding: {
    right: 10
  },
  lineSmooth: Chartist.Interpolation.cardinal({
    fillHoles: true,
  }),
  low: 0
}
```

Any advice would be great! 

Cheers,
Jens

**Comment by EvanWieland** [comment]
@jensstruemper I am also interested in using this. Please record any findings you have here!

**Comment by paradox41** [comment]
All you need to do is pass it as `options`. The interface for this lib is the same as Chartist. Let me know if any issues.

**Comment by jensstruemper** [comment]
So, that's what I tried to do. When adding the following to the options

```
lineSmooth: Chartist.Interpolation.cardinal({
    fillHoles: true,
  }),
```

I would get an exception in the browser:

```
EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in ./HomePage class HomePage_Host - inline template:0:0
ORIGINAL EXCEPTION: ReferenceError: Chartist is not defined
ORIGINAL STACKTRACE:
ReferenceError: Chartist is not defined
    at new HomePage (http://192.168.179.20:8101/build/js/app.bundle.js:68:29)
    at DebugAppView._View_HomePage_Host0.createInternal (HomePage.template.js:16:24)
    at DebugAppView.AppView.create (http://192.168.179.20:8101/build/js/app.bundle.js:31513:21)
    at DebugAppView.create (http://192.168.179.20:8101/build/js/app.bundle.js:31725:44)
    at ComponentFactory.create (http://192.168.179.20:8101/build/js/app.bundle.js:30583:36)
    at http://192.168.179.20:8101/build/js/app.bundle.js:64787:49
    at ZoneDelegate.invoke (http://192.168.179.20:8101/build/js/zone.js:323:29)
    at Object.onInvoke (http://192.168.179.20:8101/build/js/app.bundle.js:37159:41)
    at ZoneDelegate.invoke (http://192.168.179.20:8101/build/js/zone.js:322:35)
    at Zone.run (http://192.168.179.20:8101/build/js/zone.js:216:44)
ERROR CONTEXT:
[object Object]
```

Here the demo code:

```
import { Component } from '@angular/core';
import { ChartistComponent } from 'angular2-chartist';
import { NavController } from 'ionic-angular';
//import * as Chartist from 'chartist';

@Component({
//  selector: 'demo-app',
  directives: [ChartistComponent],
  template: `
    <x-chartist
      [data]="data"
      [type]="type"
      [options]="options"
      [responsiveOptions]="responsiveOptions">
    </x-chartist>
  `
})
export class HomePage {
  private data:any;
  private options:any;
  private responsiveOptions:any;
  private type:any;

  static get parameters() {
    return [[NavController]];
  }

  constructor(public navCtrl: NavController) {

  this.type = 'Line';

  this.data = {
    labels: ['1', '2', '3', '4', '5', '6'],
    series: [
              {
                data: [1, 2, null, null , 8, 13]
              }
            ]
    };

  this.options = {
    width: '300px',
    height: '200px',
    axisX: {
      lineSmooth: Chartist.Interpolation.simple({
      fillHoles: true })
    }
  }

  this.responsiveOptions = "";

  }
}
```

I can get rid of the exception my importing everything from the chartist library but the options would still have no effect: 

`import * as Chartist from 'chartist';`

**Comment by paradox41** [comment]
Well, you need to have Chartist imported. So when it is imported you are saying it doesn't work? Is there an error?

**Comment by jensstruemper** [comment]
Thanks for the confirmation! When I added `import * as Chartist from 'chartist';` the exception disappeared but the actual option had no effect (no change when setting "fillHoles from true to false"). However I just realized that the `lineSmooth` option is not working in `axisX ` context. Using it like so works as expected:

```
this.options = {
    width: '300px',
    height: '200px',
    lineSmooth: Chartist.Interpolation.simple({
      fillHoles: false })
  }
```

**Comment by paradox41** [comment]
Well, you need to have Chartist imported. So when it is imported you are
saying it doesn't work?

**Comment by jensstruemper** [comment]
Sorry if my last post wasn't clear. It is working as expected! I wasn't aware that I had to import chartist on top of angular2-chartist. Can be considered as closed.
